price section
nahirniy/Best-Full-Stack-Team-10 pull request #2
Opened 2023-08-24 09:28 UTC by bestalexlogin

Without animation

2023-08-24 10:10 UTC, nahirniy reviewed
not everything is done

2023-08-24 10:16 UTC, nahirniy requested changes
Не все зроблено.

2023-08-26 12:09 UTC, nahirniy requested changes
Потрібно внести пару не значних правок

2023-08-26 12:09 UTC, nahirniy commented on src/css/price.css
> +  display: block;
Не потрібно, ніяк не впливає на елемент

2023-08-26 12:09 UTC, nahirniy commented on src/css/price.css
> +    padding: 0 26px 100px 26px;
Не вірні падінги по бокам. Потрібно поставити вірно з макетом або краще обмежити ширину секції max-width

2023-08-26 12:09 UTC, nahirniy commented on src/css/price.css
> +  font-size: 16px;
Цей розмір шрифта йде від body. Ці стилі можна прибрати

2023-08-26 13:17 UTC, bestalexlogin commented on src/css/price.css
> +  display: block;
так дійсно воно лишнє. прибрав

2023-08-26 13:28 UTC, bestalexlogin commented on src/css/price.css
> +    padding: 0 26px 100px 26px;
Я зробив відступи зліва та справа по 156рх, тому що в макеті відступи по 172рх, та мінус 16рх контейнеру. Так має бути?

@media screen and (min-width: 1440px) {
  .price-section {
    padding: 0 156px 100px 156px;
  }
}

2023-08-26 13:29 UTC, nahirniy commented on src/css/price.css
> +    padding: 0 26px 100px 26px;
Можна так

2023-08-26 13:30 UTC, bestalexlogin commented on src/css/price.css
> +  font-size: 16px;
прибрав

2023-08-26 13:39 UTC, nahirniy commented on src/css/price.css
> +    padding: 0 26px 100px 26px;
update:

max-width тільки, падінги нажаль не підходять

2023-08-26 13:55 UTC, nahirniy approved these changes
Все чудово

2023-08-26 13:55 UTC, merged